# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/BookyWooks.sln'  # Specify the solution file
    arguments: '--configuration $(buildConfiguration)'
    
# Add step to run tests
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'  # Specify test project(s) or wildcard pattern
    arguments: '--configuration $(buildConfiguration)'

# Install Testcontainers package
- script: |
    dotnet add package TestContainers
  displayName: 'Install Testcontainers'

# Start Testcontainers for SQL Server and RabbitMQ
- script: |
    dotnet run --project path/to/BookWooks.OrderApi.TestContainersIntegrationTests.csproj
  displayName: 'Start Testcontainers'

# Add additional steps here, such as executing integration tests

# Stop Testcontainers for SQL Server and RabbitMQ
- script: |
    dotnet run --project path/to/BookWooks.OrderApi.TestContainersIntegrationTests.csproj
  displayName: 'Stop Testcontainers'