# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  BuildParameters.RestoreBuildProjects: '**/*.csproj'  # Define the variable here

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages 
  inputs:
     command: restore
     projects: $(BuildParameters.RestoreBuildProjects)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/BookyWooks.sln'
    arguments: '--configuration $(buildConfiguration)'

# - task: DockerInstaller@0  # Ensure Docker is installed
#   displayName: 'Install Docker'
#   inputs:
#     dockerVersion: '19.03.14'

# - script: |
#     docker run -d --name mssql -p 1433:1433 \
#       -e ACCEPT_EULA=Y \
#       -e SA_PASSWORD='yourStrong(!)Password' \
#       mcr.microsoft.com/mssql/server:2022-latest

#     docker run -d --name rabbitmq -p 5673:5672 \
#       -e RABBITMQ_DEFAULT_USER='guest' \
#       -e RABBITMQ_DEFAULT_PASS='guest' \
#       rabbitmq:3-management-alpine
#   displayName: 'Start Testcontainers'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: '**/BookWooks.OrderApi.TestContainersIntegrationTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
