trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DockerCompose@0
  displayName: "Run a Docker Compose command"
  inputs:
    dockerComposeFile: "docker-compose-integration-tests.yml"
    dockerComposeCommand: "up --abort-on-container-exit" 

- task: DotNetCoreCLI@2
  displayName: Restore Nuget Packages 
  inputs:
     command: restore
     projects: '**/*.csproj'
     configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    projects: '**/BookyWooks.sln'
    arguments: '--configuration $(buildConfiguration)'

- script: docker --version
  displayName: 'Print Docker Version'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test - Unit Tests'
  inputs:
    command: 'test'
    projects: '**/*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test - Exclude Integration Tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration) --filter "-not DisplayName~*IntegrationTests"'

- task: DockerCLI@2
  displayName: 'Copy Test Results'
  inputs:
    command: 'cp'
    arguments: '$(Agent.Id):/tests/booky-wooks-integration-test-results.xml $(Build.ArtifactStagingDirectory)/TestResults/'
