services:
  bookwooks.orderapi.web:
    image: ${DOCKER_REGISTRY-}bookwooksorderapiweb
    build:
      context: .
      dockerfile: BookWooks.OrderApi/src/BookWooks.OrderApi.Web/Dockerfile
    networks:
      - booky_wooks_network

  bookywooks.catalogue.api:
    image: ${DOCKER_REGISTRY-}bookywookscatalogueapi
    build:
      context: .
      dockerfile: BookyWooks.Catalogue.Api/Dockerfile
    networks:
      - booky_wooks_network

  sagaorchestration:
    image: ${DOCKER_REGISTRY-}sagaorchestration
    build:
      context: .
      dockerfile: SagaOrchestration/Dockerfile
    networks:
      - booky_wooks_network

  sqldata:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    volumes:
      - booky_wooks_sql_data:/var/opt/mssql
    networks:
      - booky_wooks_network

  statemachinedb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    networks:
      - booky_wooks_network

  identityserverdb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    volumes:
      - booky_wooks_identityserver_data:/var/lib/postgresql/data/
    networks:
      - booky_wooks_network

  postgresdb:
    image: postgres:latest
    volumes:
      - booky_wooks_postgres_data:/var/lib/postgresql/data/
    networks:
      - booky_wooks_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - booky_wooks_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    volumes:
      - elasticsearch-logs:/usr/share/elasticsearch/data
    networks:
      - booky_wooks_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    networks:
      - booky_wooks_network

  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - booky_wooks_network

  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - booky_wooks_network

  # otel-collector:
  #   image: otel/opentelemetry-collector:0.56.0
  #   command: ["--config=/etc/otel-collector-config.yaml"]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "4317:4317"
  #   networks:
  #     - booky_wooks_network

  # bookywooks.identity:
  #   image: ${DOCKER_REGISTRY-}bookywooksidentity
  #   build:
  #     context: .
  #     dockerfile: BookyWooks.Identity/Dockerfile

  ocelot.gateway:
    image: ${DOCKER_REGISTRY-}ocelotgateway
    build:
      context: .
      dockerfile: OcelotGateway/Dockerfile
    networks:
      - booky_wooks_network

  bookywooks.identityserver:
    image: ${DOCKER_REGISTRY-}bookywooksidentityserver
    build:
      context: .
      dockerfile: BookyWooks.IdentityServer/Dockerfile
    networks:
      - booky_wooks_network

volumes:
  booky_wooks_postgres_data:
  elasticsearch-logs:
  booky_wooks_sql_data:
  booky_wooks_identityserver_data:
  
networks:
  booky_wooks_network:
    external: true