version: '3.4'

services:
  bookwooks.orderapi.web:
    container_name: bookwooks.orderapi.web
    environment:

      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=sqldata;Database=BookyWooks.OrderDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=true;"
      - RabbitMQConfiguration__Config__HostName=${BOOKYWOOKS_RABBITMQ_HOSTNAME:-rabbitmq}
      - RabbitMQConfiguration__Config__UserName=${BOOKYWOOKS_RABBITMQ_USERNAME:-guest}
      - RabbitMQConfiguration__Config__Password=${BOOKYWOOKS_RABBITMQ_PASSWORD:-guest}
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - Jaeger__Protocol=http
      - Jaeger__Port=4317
      - Jaeger__Host=jaeger
    ports:
      - "5001:8080"
      - "5002:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  bookywooks.catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=8081
      - "ConnectionStrings__Database=Server=postgresdb;Database=CatalogueDb;User Id=admin;Password=admin1234;"
      - RabbitMQConfiguration__Config__HostName=${BOOKYWOOKS_RABBITMQ_HOSTNAME:-rabbitmq}
      - RabbitMQConfiguration__Config__UserName=${BOOKYWOOKS_RABBITMQ_USERNAME:-guest}
      - RabbitMQConfiguration__Config__Password=${BOOKYWOOKS_RABBITMQ_PASSWORD:-guest}
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - Jaeger__Protocol=http
      - Jaeger__Port=4317
      - Jaeger__Host=jaeger
    ports:
      - "5007:8080"
      - "5009:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  
  sagaorchestration:
    environment:
      - DOTNET_ENVIRONMENT=Development
      - "ConnectionStrings__DefaultConnection=Server=statemachinedb;Database=StateMachineDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true;TrustServerCertificate=true;"
      - RabbitMQConfiguration__Config__HostName=${BOOKYWOOKS_RABBITMQ_HOSTNAME:-rabbitmq}
      - RabbitMQConfiguration__Config__UserName=${BOOKYWOOKS_RABBITMQ_USERNAME:-guest}
      - RabbitMQConfiguration__Config__Password=${BOOKYWOOKS_RABBITMQ_PASSWORD:-guest}
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
      - Jaeger__Protocol=http
      - Jaeger__Port=4317
      - Jaeger__Host=jaeger

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-logs:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  jaeger:
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 4317:4317
      - 4318:4318
      - 9411:9411
    environment:
      COLLECTOR_OTLP_ENABLED: true

  prometheus:
    ports:
      - "9090:9090"

networks:
  booky_wooks_network:
    external: true
