global using Ardalis.ListStartupServices;
global using BookWooks.OrderApi.Core;
global using BookWooks.OrderApi.Infrastructure;
global using FastEndpoints;
global using FastEndpoints.Swagger;
global using Serilog;
global using BookWooks.OrderApi.UseCases;
global using BookWooks.OrderApi.UseCases.Orders;
global using BookWooks.OrderApi.UseCases.Create;
global using BookyWooks.SharedKernel;
global using MediatR;
global using BookWooks.OrderApi.UseCases.Orders.List;
global using BookWooks.OrderApi.UseCases.Orders.Get;
global using BookWooks.OrderApi.Web.Orders;
global using BookWooks.OrderApi.UseCases.Cancel;
global using BookWooks.OrderApi.Infrastructure.Data.Extensions;
global using Logging;
global using Tracing;

