global using Xunit;
global using BookWooks.OrderApi.Infrastructure.Data;
global using BookWooks.OrderApi.UseCases.Create;
global using BookWooks.OrderApi.Core.OrderAggregate.Entities;
global using BookyWooks.Messaging.Contracts.Commands;
global using BookyWooks.Messaging.Messages.InitialMessage;
global using FluentAssertions;
global using IntegrationTestingSetup;
global using MassTransit.Testing;
global using OrderItem = BookWooks.OrderApi.UseCases.Create.OrderItem;
global using BookWooks.OrderApi.TestContainersIntegrationTests.Consumers;
global using MassTransit;
global using BookyWooks.Messaging.Contracts.Events;
global using Microsoft.Extensions.DependencyInjection;